name: Deploy Flask App

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
	with:
 	  python-version: 3.12

      - name: Install Dependencies
      	run: python -m pip install --upgrade pip
       
      - name: Install Libraries
        run: pip install -r requirements.txt

      - name: Update Code
        run: sed -i 's/Hello World/Hello David/' app.py

      - name: Build Docker Image
        run: |
	  docker build -t flaskproject .
   	  docker tag flaskproject filipdavid/flaskrepo:latest

deploy:
  runs-on: ubuntu-latest

  steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
	aws-secret-acess-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 	aws-region: eu-north-1

    - name: Push Docker Image to Registry
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docekr login -u ${{ secerts.DOCKER_USERNAME }} --password-stdin

    - name: Initialize Terraform
      run: terraform init

    - name: Apply Terraform Changes
      run: terraform apply
